spring:
  application:
    name: crawler-eureka

server:
  port: 6660
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
       defaultZone: http://localhost:${server.port}/eureka/



